# Generated by Django 5.1.3 on 2024-12-08 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lugar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lugar',
            name='fecha_creacion',
        ),
    ]
